const express = require("express");
const app = express();
const cookieParser = require("cookie-parser");
const BodyParser = require("body-parser");
const Upload = require("express-fileupload");
const path = require("path");
const ApplyMiddleware = require("./Middleware/ErrorCallBackReturn");
const cors = require("cors");
const CountryRoutes = require("./Routes/CountryRoutes");
const StateRoutes = require("./Routes/StateRoutes");
const CityRoutes = require("./Routes/CityRoutes");
const AttendanceRoutes = require("./Routes/AttendanceRoutes");
const CeoRoutes = require("./Routes/CeoRoutes");
const CompanyDetailRoutes = require("./Routes/CompanyDetailRoutes");
const CompanyThemeRoutes = require("./Routes/CompanyThemeRoutes");
const DesignationRoutes = require("./Routes/DesignationRoutes");
const EmployeeRoutes = require("./Routes/EmployeeRoutes");
const EmployeeTaskRoutes = require("./Routes/EmployeeTaskRoutes");
const MartialStatusRoutes = require("./Routes/MartialStatusRoutes");
const OrganizationDetailRoutes = require("./Routes/OrganizationDetailRoutes");
const OrganizationTypeRoutes = require("./Routes/OrganizationTypeRoutes");
const ProjectRoutes = require("./Routes/ProjectRoutes");
const EmployeeDocumentRoutes = require("./Routes/EmployeeDocumentRoutes");
const ProjectSectionRoutes = require("./Routes/ProjectSectionRoutes");
const MeetingRoutes = require("./Routes/MeetingRoutes");
const ChatRoutes = require("./Routes/ChatRoutes");

app.use(express.json());
app.use(cookieParser());
app.use(BodyParser.urlencoded({ extended: true }));
app.use(Upload());
app.use(cors());
app.use("/api/Chat", ChatRoutes);
app.use("/api/Meeting", MeetingRoutes);
app.use("/api/ProjectSection", ProjectSectionRoutes);
app.use("/api/Country", CountryRoutes);
app.use("/api/State", StateRoutes);
app.use("/api/Attendance", AttendanceRoutes);
app.use("/api/Ceo", CeoRoutes);
app.use("/api/CompanyDetail", CompanyDetailRoutes);
app.use("/api/CompanyTheme", CompanyThemeRoutes);
app.use("/api/Designation", DesignationRoutes);
app.use("/api/Employee", EmployeeRoutes);
app.use("/api/EmployeeTask", EmployeeTaskRoutes);
app.use("/api/MartialStatus", MartialStatusRoutes);
app.use("/api/OrganizationDetail", OrganizationDetailRoutes);
app.use("/api/OrganizationType", OrganizationTypeRoutes);
app.use("/api/Project", ProjectRoutes);
app.use("/api/EmployeeDocument", EmployeeDocumentRoutes);
app.use("/api/City", CityRoutes);

app.use(ApplyMiddleware);

module.exports = app;
